version: '3'

services:
  liferay:
    restart: always
    build:
      context: ./
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    labels:
      tier: tomcat
      app: liferay
    ports:
      - 8080:8080
    volumes:
      - ./liferay-home:/data
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:9.6-alpine
    labels:
      tier: data
      app: liferay
    environment:
      POSTGRES_INITDB_ARGS: --encoding UNICODE --locale C --lc-collate C --lc-ctype C
      POSTGRES_USER: liferay
      POSTGRES_PASSWORD: liferay
    volumes:
      - ./liferay-db:/var/lib/postgresql/data

